version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - revive
    - misspell
    - prealloc
    - unconvert
    - unparam
    - gofumpt

formatters:
  enable:
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
