// Code generated by genrecorder; DO NOT EDIT.

package idem

import (
	"io"
	"net/http"
)

// responseRecorderFlusherHijackerReaderFrom delegates http.Flusher, http.Hijacker,
// and io.ReaderFrom to the underlying ResponseWriter.
type responseRecorderFlusherHijackerReaderFrom struct {
	*responseRecorder
	http.Flusher
	http.Hijacker
	io.ReaderFrom
}

// responseRecorderHijackerReaderFrom delegates both http.Hijacker and io.ReaderFrom
// to the underlying ResponseWriter.
type responseRecorderHijackerReaderFrom struct {
	*responseRecorder
	http.Hijacker
	io.ReaderFrom
}

// responseRecorderFlusherReaderFrom delegates both http.Flusher and io.ReaderFrom
// to the underlying ResponseWriter.
type responseRecorderFlusherReaderFrom struct {
	*responseRecorder
	http.Flusher
	io.ReaderFrom
}

// responseRecorderReaderFrom delegates io.ReaderFrom to the underlying ResponseWriter.
type responseRecorderReaderFrom struct {
	*responseRecorder
	io.ReaderFrom
}

// responseRecorderFlusherHijacker delegates both http.Flusher and http.Hijacker
// to the underlying ResponseWriter.
type responseRecorderFlusherHijacker struct {
	*responseRecorder
	http.Flusher
	http.Hijacker
}

// responseRecorderHijacker delegates http.Hijacker to the underlying ResponseWriter.
type responseRecorderHijacker struct {
	*responseRecorder
	http.Hijacker
}

// responseRecorderFlusher delegates http.Flusher to the underlying ResponseWriter.
type responseRecorderFlusher struct {
	*responseRecorder
	http.Flusher
}

func newResponseRecorder(w http.ResponseWriter) http.ResponseWriter {
	rec := &responseRecorder{
		ResponseWriter: w,
		statusCode:     http.StatusOK,
	}

	flusher, canFlush := w.(http.Flusher)
	hijacker, canHijack := w.(http.Hijacker)
	readerFrom, canReadFrom := w.(io.ReaderFrom)

	switch {
	case canFlush && canHijack && canReadFrom:
		return &responseRecorderFlusherHijackerReaderFrom{rec, flusher, hijacker, readerFrom}
	case canHijack && canReadFrom:
		return &responseRecorderHijackerReaderFrom{rec, hijacker, readerFrom}
	case canFlush && canReadFrom:
		return &responseRecorderFlusherReaderFrom{rec, flusher, readerFrom}
	case canReadFrom:
		return &responseRecorderReaderFrom{rec, readerFrom}
	case canFlush && canHijack:
		return &responseRecorderFlusherHijacker{rec, flusher, hijacker}
	case canHijack:
		return &responseRecorderHijacker{rec, hijacker}
	case canFlush:
		return &responseRecorderFlusher{rec, flusher}
	default:
		return rec
	}
}
