// Code generated by genrecorder; DO NOT EDIT.

package idem

import (
	"bufio"
	"io"
	"net"
	"net/http"
)

// plainWriter implements only http.ResponseWriter.
type plainWriter struct {
	http.ResponseWriter
}

// flusherWriter implements http.ResponseWriter and http.Flusher.
type flusherWriter struct {
	http.ResponseWriter
	flushed bool
}

func (w *flusherWriter) Flush() {
	w.flushed = true
}

// hijackerWriter implements http.ResponseWriter and http.Hijacker.
type hijackerWriter struct {
	http.ResponseWriter
	hijacked bool
}

func (w *hijackerWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	w.hijacked = true
	return nil, nil, nil
}

// flusherHijackerWriter implements http.ResponseWriter, http.Flusher,
// and http.Hijacker.
type flusherHijackerWriter struct {
	http.ResponseWriter
	flushed  bool
	hijacked bool
}

func (w *flusherHijackerWriter) Flush() {
	w.flushed = true
}

func (w *flusherHijackerWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	w.hijacked = true
	return nil, nil, nil
}

// readerFromWriter implements http.ResponseWriter and io.ReaderFrom.
type readerFromWriter struct {
	http.ResponseWriter
	readFrom bool
}

func (w *readerFromWriter) ReadFrom(r io.Reader) (int64, error) {
	w.readFrom = true
	return io.Copy(w.ResponseWriter, r)
}

// flusherReaderFromWriter implements http.ResponseWriter, http.Flusher,
// and io.ReaderFrom.
type flusherReaderFromWriter struct {
	http.ResponseWriter
	flushed  bool
	readFrom bool
}

func (w *flusherReaderFromWriter) Flush() {
	w.flushed = true
}

func (w *flusherReaderFromWriter) ReadFrom(r io.Reader) (int64, error) {
	w.readFrom = true
	return io.Copy(w.ResponseWriter, r)
}

// hijackerReaderFromWriter implements http.ResponseWriter, http.Hijacker,
// and io.ReaderFrom.
type hijackerReaderFromWriter struct {
	http.ResponseWriter
	hijacked bool
	readFrom bool
}

func (w *hijackerReaderFromWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	w.hijacked = true
	return nil, nil, nil
}

func (w *hijackerReaderFromWriter) ReadFrom(r io.Reader) (int64, error) {
	w.readFrom = true
	return io.Copy(w.ResponseWriter, r)
}

// flusherHijackerReaderFromWriter implements http.ResponseWriter, http.Flusher, http.Hijacker,
// and io.ReaderFrom.
type flusherHijackerReaderFromWriter struct {
	http.ResponseWriter
	flushed  bool
	hijacked bool
	readFrom bool
}

func (w *flusherHijackerReaderFromWriter) Flush() {
	w.flushed = true
}

func (w *flusherHijackerReaderFromWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	w.hijacked = true
	return nil, nil, nil
}

func (w *flusherHijackerReaderFromWriter) ReadFrom(r io.Reader) (int64, error) {
	w.readFrom = true
	return io.Copy(w.ResponseWriter, r)
}
